version: '3'

services:
  db:
    image: 'postgres:12-alpine'
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'

  redis:
    image: 'redis:6-alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  web:
    depends_on:
      - 'db'
      - 'redis'
      - 'webpacker'
    build: .
    env_file:
      - '.env'
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'

  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: bundle exec sidekiq
    volumes:
      - '.:/app'
      - '/app/tmp' # don't mount tmp directory

  webpacker:
    build: .
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    command: ./bin/webpack-dev-server
    volumes:
      - '.:/app'
    ports:
      - '3035:3035'
volumes:
  redis: {}

