default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host:     <%= ENV['APP_DB_HOST'] || 'localhost' %>
  database: <%= ENV['APP_DB_NAME'] %>
  username: <%= ENV['APP_DB_USERNAME'] || 'root' %>
  password: <%= ENV['APP_DB_PASSWORD'] || '' %>

development:
  <<: *default
  database: hyper_kitten_development

test:
  <<: *default
  database: hyper_kitten_test
